spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subject_jpa
    username: ohgiraffers
    password: ohgiraffers

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create # create, update, validate, none are possible ,???? create, ??


    properties:
      hibernate:
        format_sql: true
